### ISSUE TITLE
Pipenv no longer working under the root directory

### ISSUE THREAD

**Issue by pradumangoyal** [IMGIITRoorkee/omniport-docker#30]
**Describe the bug**
pipenv in its latest change no longer work under the root directory, giving the error 
`ERROR: Pipenv is not intended to work under the root directory, please choose another path.` while building the Django container.

**To Reproduce**
Try to build the Django container by `./scripts/build/django.sh`

For reference: pypa/pipenv#4273

**Comment by dhruvkb** [comment]
This is some grade A bullshit from Pipenv.

**Comment by dhruvkb** [comment]
Can we try switching to Poetry?
